---
- name: Make sure extraction directory is present
  file: path={{networker_package_path}} state=directory

- name: Download and extract software
  unarchive: dest={{networker_package_path}} src={{networker_package_url}} copy=no creates='{{networker_package_path}}/linux_x86_64'

- import_tasks: server.yml
  when: networker_mode == 'server'

- import_tasks: client.yml
  when: networker_mode == 'client'
