---
- name: Install Networker server
  yum: name='{{networker_package_path}}/linux_x86_64/{{item}}-{{networker_version}}.x86_64.rpm' state=present
  with_items: '{{networker_packages.server}}'
  notify: Restart networker

- name: Enable and start server service
  service: name=networker state=started enabled=yes
